actor_lr: 0.0001
critic_lr: 0.001
max_memory: 1000000
episode: 500
batch_size: 64
gamma: 0.99
tau: 0.005
policy_noise: 0.2
noise_clip: 0.5
min_action: -1.0
max_action: 1.0
max_grad_norm: 0.5
target_update_steps: 1