episode: 2000                  
gamma: 0.99
epsilon: 1.0
epsilon_decay: 0.995 
epsilon_min: 0.01               
learning_rate: 0.001      
max_memory: 100000              
batch_size: 128                 
target_update_steps: 500
n_step: 10
actor_lr: 0.001  
critic_lr: 0.001  
